### ISSUE TITLE
协作

### ISSUE THREAD

**Issue by olOwOlo** [illyasviel/crowds#1]
- [x] section 0 【olOwOlo 基本完成】#3
- [x] section 1 【olOwOlo 基本完成】#4
- [x] section 2 【olOwOlo 基本完成】#5
- [x] section 3 【olOwOlo 基本完成】#13
- [x] section 4 【lxdlam 基本完成】#7
- [x] section 5 【5thgfka 基本完成】#11
- [x] section 6 【lxdlam 基本完成】#9
- [x] section 7 【lxdlam 基本完成】#8
- [x] REFERENCES 【appleseed0910 基本完成】#14
- [x] BONUS BOXES 【appleseed0910 基本完成】#14
---
翻译工作在 zh-CN 分支进行，最好在此分支的基础上再新建一个分支，注意是推送到 zh-CN 分支，不要推到主仓库或是这个仓库的别的分支上了
开始前先留言说一下翻译哪个片段以免冲突，我会实时更新这个列表，完成后推送到 zh-CN 分支即可

**Comment by olOwOlo** [comment]
@appleseed0910

**Comment by appleseed0910** [comment]
gotcha

**Comment by appleseed0910** [comment]
我这边有时差！半夜三点（）小哥哥你先翻着 我睡一觉起来弄一下（这个人怎么这样
我比较喜欢翻reference和注释一类的东西 XD不要在意

**Comment by appleseed0910** [comment]
还有一些学术名词到时候要统一一下的吧！

**Comment by 5thgfka** [comment]
请问怎么加入呢？

**Comment by olOwOlo** [comment]
@appleseed0910 
没关系~\~你先睡吧~~
我进度太慢，还没碰到什么学术名词（#捂脸，碰到了我标记一下到时候再讨论吧？

**Comment by olOwOlo** [comment]
@5thgfka 
主要以游戏下方的 0 - 7 个阶段划分，大部分内容都在这里了，开始前先说一下要翻哪一段以免冲突

**Comment by 5thgfka** [comment]
section 5 如何？

**Comment by olOwOlo** [comment]
@5thgfka 👌

**Comment by lxdlam** [comment]
还有位置吗 我今晚把这个游戏玩穿一遍也来认领一个

**Comment by olOwOlo** [comment]
@lxdlam 可以啊，还没好多没翻呢，

**Comment by lxdlam** [comment]
第四节给我吧

**Comment by olOwOlo** [comment]
@lxdlam 👌

**Comment by lxdlam** [comment]
接下来我先把 section 7 搞定吧~

**Comment by olOwOlo** [comment]
@lxdlam 👌

**Comment by lxdlam** [comment]
@olOwOlo 我认领一下 section 6 吧，reference和bouns boxes我粗略看了一下好像搞不定_(:зゝ∠)_

**Comment by olOwOlo** [comment]
@lxdlam 好的，希望睡觉的小哥哥来帮忙解决这个 🤣

**Comment by lxdlam** [comment]
小哥哥小姐姐们加油，我睡啦 :sleeping_bed:

**Comment by 5thgfka** [comment]
我大致翻完了，不过不太会push上去，明天起来看看。先睡了。

**Comment by appleseed0910** [comment]
我回来啦 我认领reference+bonus！（搓手手 working in progress... 大家都好迅速哇！我会小心翼翼地翻的~
// btw我不是小哥哥XDD

**Comment by 5thgfka** [comment]
对于翻译我一直有个不清楚的地方，当翻译到某某某的论文或者书时，论文名称和书名是不是要翻译？

**Comment by appleseed0910** [comment]
@5thgfka 
我翻译的时候也纠结了一下！我一开始是没有翻译的，因为觉得有点可能会过度翻译/以及考虑到想看文章的人自己会去看
不过后来想想 一般来说别的翻译作品里如果出现了拉丁文/西班牙语/法语/德语这种非文本本体的语言（引用语/诗歌文摘/书名论文） 也会选择翻译，所以就尝试翻译了一下
毕竟会选择用被翻译的语言浏览的用户也会想说希望自己接受到的信息是尽可能多的被处理过的（？
不过这说到底是个很琐碎的问题XD不要太在意

**Comment by antfu** [comment]
Sandbox 是不是还没有人翻译？😏

**Comment by appleseed0910** [comment]
翻了 致谢也翻了

Anthony Fu <notifications@github.com> 于 2018年5月3日周四 04:32写道：

**Comment by appleseed0910** [comment]
Emmm 我看了下讨论串好像不太确定(陷入了:难道我没有翻吗？的疑问
不过没翻的话 补上也好 白天到了我又要消失了😂 诸君加油

Xinyi Hu <hu.xinyi@husky.neu.edu> 于 2018年5月3日周四 09:47写道：
